port: 53
httpPort: 4000
upstream:
  default:
  - tcp-tls:1.1.1.1:853
  - tcp-tls:1.0.0.1:853
blocking:
  blackLists:
    ads:
    - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
  clientGroupsBlock:
    default:
    - ads
